export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const INIT_BURGER='INIT_BURGER';
export const INIT_BURGER_ERROR='INIT_BURGER_ERROR';

export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START_REQ='PURCHASE_BURGER_START_REQ';
export const SHOW_CHECKOUT='SHOW_CHECKOUT';

export const FETCH_ORDERS_REQ_START='FETCH_ORDERS_REQ_START'
export const FETCH_ORDERS_REQ_SUCCESS='FETCH_ORDERS_REQ_SUCCESS'
export const FETCH_ORDERS_REQ_FAIL='FETCH_ORDERS_REQ_FAIL'

export const AUTH_REQ_START='AUTH_REQ_START';
export const AUTH_REQ_FAIL='AUTH_REQ_FAIL';
export const AUTH_REQ_SUCCESS='AUTH_REQ_SUCCESS';
export const AUTH_CLEAR_ERROR='AUTH_CLEAR_ERROR'