export const ADD_INGREDIENT='ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const INIT_BURGER='INIT_BURGER';
export const INIT_BURGER_ERROR='INIT_BURGER_ERROR';

export const PURCHASE_BURGER_SUCCESS='PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL='PURCHASE_BURGER_FAIL';
