const ADD_INGREDIENT='ADD_INGREDIENT';
const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
const RESET_INGREDIENTS='RESET_INGREDIENTS';
module.exports={
    ADD_INGREDIENT,
    REMOVE_INGREDIENT,
    RESET_INGREDIENTS
}